name: CI/CD Pipeline (develop only - buildx, no cache, multi-platform)

on:
  push:
    branches: [develop, test]
  pull_request:
    branches: [develop]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      IMAGE_NAME: zerojae175/easy-schedule
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push development image (no cache, multi-platform)
        run: |
          echo "Building image (no cache, amd64/arm64)..."
          docker buildx build \
            --no-cache \
            --platform linux/amd64,linux/arm64 \
            -f Dockerfile \
            -t ${IMAGE_NAME}:dev_${IMAGE_TAG} \
            --push .
